[global]

# By default, Streamlit checks if the Python watchdog module is available and, if not, prints a warning asking for you to install it. The watchdog module is not required, it's just useful. If you'd like to suppress this warning, set this to True.
disableWatchdogWarning = false

# Configure the ability to share
sharingMode = "off"

# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
showWarningOnDirectExecution = true

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

[client]

# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not connect to the Streamlit servers.
gatherUsageStats = true

[browser]

# Internet address where users should point their browsers in order to connect to the app. Can be IP address or DNS name and path.
serverAddress = "localhost"

# Port where users should point their browsers in order to connect to the app.
serverPort = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

[server]

# List of folders that should not be watched for changes. This impacts both "Run on Save" and @st.cache.
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas, this should be set to the same value across all replicas to ensure they all share the same secret.
cookieSecret = "auto"

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = false

# The address where the server will listen for client and browser connections. Use this if you want to bind the server to a specific address. If set, the server will only be accessible from this address, and not from any other address.
address = "localhost"

# The port number where the server will listen for client and browser connections.
port = 8501

# Enables support for Cross-Origin Resource Sharing (CORS) for the given domains. Wildcard "*" is supported.
enableCORS = false

# Enables support for Cross-Origin Resource Sharing (CORS) for WebSocket connections.
enableWebsocketCompression = true

[theme]

# Primary accent color for interactive elements.
primaryColor = "#FF6B6B"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#262730"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"
