# Streamlit Secrets Configuration
# Add your API keys here - at least one is required for the app to work

# OpenAI API Key (get from: https://platform.openai.com/api-keys)
OPENAI_API_KEY = "your_openai_api_key_here"

# Anthropic API Key (get from: https://console.anthropic.com/)
ANTHROPIC_API_KEY = "your_anthropic_api_key_here"

# Google Gemini API Key (get from: https://aistudio.google.com/)
GEMINI_API_KEY = "your_gemini_api_key_here"

# Note: You only need to configure the API keys for the services you want to use
# The app will automatically detect which providers are available based on configured keys
